In [2]:
import numpy as np 
import pandas as pd 
from sklearn import preprocessing
import matplotlib.pyplot as plt 
import seaborn as sns

In [26]:
data = pd.read_csv(r"C:\Users\dipak\OneDrive\desktop\AIML\Heart_disease_predictions\framingham (1).csv")

In [27]:
data.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [28]:
print(data.columns)

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [29]:
# Here the column education doesnt contribute any value to the heart disease so it is dropped

In [30]:
data.drop(columns=["education"], inplace = True)

In [31]:
data.rename(columns = {"male":"Sex_male"}, inplace=True)

In [32]:
data.dropna(axis=0, inplace=True)

In [33]:
data.head()

,Sex_male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [34]:
data.TenYearCHD.value_counts()

TenYearCHD
0    3179
1     572
Name: count, dtype: int64

In [36]:
X = np.asarray(data[["age","Sex_male","cigsPerDay","totChol","sysBP","glucose"]])

In [37]:
y = np.array(data["TenYearCHD"])

In [39]:
print(X[:6])

[[ 39.    1.    0.  195.  106.   77. ]
 [ 46.    0.    0.  250.  121.   76. ]
 [ 48.    1.   20.  245.  127.5  70. ]
 [ 61.    0.   30.  225.  150.  103. ]
 [ 46.    0.   23.  285.  130.   85. ]
 [ 43.    0.    0.  228.  180.   99. ]]

In [43]:
X = preprocessing.StandardScaler().fit(X).transform(X)